server:
    port: 8081
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

gateway:
    url: http://localhost:8080

spring:
    profiles:
        active: local
    jackson:
        property-naming-strategy: LOWER_CAMEL_CASE
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: Asia/Seoul
    datasource:
        # MariaDB JDBC URL
        url: jdbc:mariadb://192.168.0.232:3306/MVIMS?autoReconnect=true&tcpKeepAlive=true
        username: mvims
        password: 1234   # 비밀번호가 그대로라면 유지, 아니면 MariaDB용으로 변경
        driver-class-name: org.mariadb.jdbc.Driver

        hikari:
            maximum-pool-size: 10
            idle-timeout: 120000         # 2분 (max-lifetime보다 작게 설정)
            max-lifetime: 180000         # 3분
            connection-timeout: 30000
            keepalive-time: 60000        # 1분 (커넥션 유효성 주기적 체크)

    jpa:
        show-sql: false
        properties:
            hibernate:
                hbm2ddl:
                    auto: none
                format_sql: true
                use_sql_comments: false  # SQL 주석을 비활성화하여 주석 없이 출력
        database: mysql
        database-platform: org.hibernate.dialect.MariaDB103Dialect
    thymeleaf:
        cache: false
        check-template-location: true
        prefix: classpath:/templates/
        suffix: .html
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    messages:
        basename : exceptionMessage
        encoding : UTF-8

mybatis:
    config-location: classpath:/mybatis-config.xml
    mapper-locations: classpath*:/mybatis*/**/*.xml

logging:
    level:
        root: INFO
        com.system: DEBUG
        org.apache.ibatis: DEBUG
        java.sql: DEBUG
        org.springframework.jdbc: DEBUG